package fulhash

import (
	cruciblefulhash "github.com/fulmenhq/crucible/fulhash"
)

// Algorithm represents a supported hashing algorithm.
// This type is imported directly from Crucible's generated types to ensure
// SSOT compliance and prevent drift across gofulmen, pyfulmen, and tsfulmen.
//
// Source: schemas/crucible-go/taxonomy/library/fulhash/algorithms/v1.0.0/algorithms.yaml
// Generated by: github.com/fulmenhq/crucible@v0.2.20
type Algorithm = cruciblefulhash.Algorithm

// Re-export Crucible algorithm constants.
// These are generated from the SSOT taxonomy and include all supported algorithms.
const (
	// XXH3_128 is the default fast non-cryptographic algorithm.
	// Excellent collision resistance, extremely high throughput (50GB/s+).
	XXH3_128 = cruciblefulhash.XXH3_128

	// SHA256 is the cryptographic algorithm for security-sensitive use cases.
	// Resistant to intentional collisions. Use for security verification.
	SHA256 = cruciblefulhash.SHA256

	// CRC32 is the 32-bit Cyclic Redundancy Check (IEEE polynomial).
	// Standard for GZIP/ZIP/PNG legacy format interoperability.
	CRC32 = cruciblefulhash.CRC32

	// CRC32C is the 32-bit CRC (Castagnoli polynomial).
	// Hardware accelerated (SSE4.2/ARMv8). Use for cloud storage (GCS, AWS) and networking.
	CRC32C = cruciblefulhash.CRC32C
)
