// Package foundry provides foundation utilities for Go applications.
//
// This package includes:
//   - RFC3339Nano timestamp generation
//   - UUIDv7 correlation ID generation
//   - Pattern matching from Crucible catalogs
//   - MIME type detection
//   - HTTP status helpers
package foundry

import (
	"time"
)

// UTCNowRFC3339Nano returns the current UTC time in RFC3339 format with nanosecond precision.
//
// The format matches the RFC3339Nano layout with 'Z' timezone indicator, conforming
// to Crucible logging standards for consistent cross-language timestamp representation.
//
// Example output: "2025-10-13T14:32:15.123456789Z"
//
// This function is suitable for:
//   - Log event timestamps
//   - Trace span timestamps
//   - Metric event timestamps
//   - Any structured data requiring precise temporal ordering
//
// Note: Go's time.RFC3339Nano provides nanosecond precision, while Python's
// implementation provides microsecond precision due to datetime limitations.
// Both formats are compatible and sortable.
func UTCNowRFC3339Nano() string {
	return time.Now().UTC().Format(time.RFC3339Nano)
}

// FormatRFC3339Nano formats a time.Time value as RFC3339Nano with 'Z' timezone indicator.
//
// This is useful when you have an existing time.Time value and want to format it
// consistently with UTCNowRFC3339Nano.
//
// Example:
//
//	t := time.Date(2025, 10, 13, 14, 32, 15, 123456789, time.UTC)
//	formatted := FormatRFC3339Nano(t)
//	// Output: "2025-10-13T14:32:15.123456789Z"
func FormatRFC3339Nano(t time.Time) string {
	return t.UTC().Format(time.RFC3339Nano)
}

// ParseRFC3339Nano parses an RFC3339Nano formatted string into a time.Time value.
//
// This handles timestamps generated by UTCNowRFC3339Nano and is lenient with
// fractional seconds precision (supports microsecond and nanosecond precision).
//
// Example:
//
//	t, err := ParseRFC3339Nano("2025-10-13T14:32:15.123456789Z")
//	if err != nil {
//	    // Handle error
//	}
//	// Use t as time.Time
func ParseRFC3339Nano(s string) (time.Time, error) {
	return time.Parse(time.RFC3339Nano, s)
}
